# Generated by Django 4.0.5 on 2023-07-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='designation',
            field=models.CharField(choices=[('Skull', 'Skull'), ('BOT', 'BOT'), ('Dechand', 'Deckhand')], default='', max_length=200),
        ),
    ]
