# Generated by Django 4.0.5 on 2023-07-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_payment_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Which_Is_Your_Preferred_Meal_For_the_Convaj_Dinner_Your_Choice_Will_Be_Indicated_on_Your_Meal_Ticket',
            field=models.CharField(choices=[('Rice with Assorted Protein', 'Rice with Assorted Protein'), ('Swallow with assorted protein', 'Swallow with assorted protein')], default='', max_length=200),
        ),
    ]
